<a href="https://colab.research.google.com/github/epigos/learning-pytorch/blob/master/01-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print('device:', device)

device: cpu


In [3]:
torch.rand(2, 2)

tensor([[0.1514, 0.2098],
        [0.6448, 0.8204]])

In [4]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [6]:
torch.rand(1).item()

0.7239357233047485

In [7]:
torch.rand(2, 2).max()

tensor(0.9246)

In [8]:
torch.rand(2, 2).max().item()

0.5647392272949219

In [9]:
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [10]:
long_tensor

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [0]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [12]:
float_tensor.type()

'torch.FloatTensor'

In [13]:
float_tensor

tensor([[0., 0., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])

In [14]:
random_tensor = torch.rand(2, 2)
random_tensor.log2()

tensor([[-0.0814, -5.8371],
        [-0.4657, -1.0376]])

In [15]:
random_tensor.log2_()

tensor([[-0.0814, -5.8371],
        [-0.4657, -1.0376]])

In [0]:
# reshaping data
flat_tensor = torch.rand(784)

In [17]:
flat_tensor.view(1, 28, 28).shape

torch.Size([1, 28, 28])

In [18]:
flat_tensor.reshape(1, 28, 28).shape

torch.Size([1, 28, 28])

In [19]:
torch.Size([1, 28, 28])

torch.Size([1, 28, 28])

In [0]:
# rearrange dimensions
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)

In [21]:
chw_tensor.shape

torch.Size([3, 640, 480])