In [1]:
import torch

In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print('device:', device)

device: cpu


In [3]:
torch.rand(2, 2)

tensor([[0.7127, 0.2690],
        [0.6926, 0.6823]])

In [4]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [6]:
torch.rand(1).item()

0.31113845109939575

In [7]:
torch.rand(2, 2).max()

tensor(0.7865)

In [8]:
torch.rand(2, 2).max().item()

0.7230761647224426

In [9]:
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [10]:
long_tensor

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [11]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [12]:
float_tensor.type()

'torch.FloatTensor'

In [13]:
float_tensor

tensor([[0., 0., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])

In [14]:
random_tensor = torch.rand(2, 2)
random_tensor.log2()

tensor([[-3.2163, -0.0603],
        [-1.0597, -5.2001]])

In [15]:
random_tensor.log2_()

tensor([[-3.2163, -0.0603],
        [-1.0597, -5.2001]])

In [16]:
# reshaping data
flat_tensor = torch.rand(784)

In [17]:
flat_tensor.view(1, 28, 28).shape

torch.Size([1, 28, 28])

In [18]:
flat_tensor.reshape(1, 28, 28).shape

torch.Size([1, 28, 28])

In [19]:
torch.Size([1, 28, 28])

torch.Size([1, 28, 28])

In [20]:
# rearrange dimensions
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)

In [21]:
chw_tensor.shape

torch.Size([3, 640, 480])